### ISSUE TITLE
Vip "Ice Scan - Super Mario Bros. 3" makes generator confused and fails generating wiki template

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [AAAAAAidan/Rip-Template-Generator#4]
The rip in question: https://www.youtube.com/watch?v=fUmr71CheIE

This rip's description ends after the platform line, which make generator throws TypeError and stopped working.

```
Uncaught TypeError: platformPattern.exec(...) is null
    onreadystatechange https://siivagunner-database.github.io/Rip-Template-Generator/script.js:174
    generateTemplate https://siivagunner-database.github.io/Rip-Template-Generator/script.js:75
    onsubmit https://siivagunner-database.github.io/Rip-Template-Generator/:1
4 script.js:174:60
```

**Comment by AAAAAAidan** [comment]
Thank you for your report. I will look into a fix for this.

**Comment by AAAAAAidan** [comment]
The bug has been resolved in the [most  recent commit](https://github.com/SiIvaGunner-Database/Rip-Template-Generator/commit/8de0e9e1329162ec20fc57938c48fd3e46563a8e). Please let me know if you encounter any more issues.
